name: Waka Stats

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SECTION_NAME: "SECTIONTN"
          LOCALE: "en"
          SHOW_LINES_OF_CODE: true
          SHOW_OS: true
          SHOW_TOTAL_CODE_TIME: true
          SHOW_PROFILE_VIEWS: true
          SHOW_LANGUAGE: true
          SHOW_PROJECTS: true
          SHOW_EDITORS: true
          SHOW_LANGUAGE_PER_REPO: true
          SHOW_TIMEZONE: false
          SHOW_LOC_CHART: false
          COMMIT_MESSAGE: "Hello gentelmen, I am updating my wakatime stats."
